export default {
  ERROR_INPUT_VALIDATION: 'ERROR_INPUT_VALIDATION',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  ERROR_UNKNOWN: 'ERROR_UNKNOWN',
  ACCOUNT_DOES_NOT_EXIST: 'ACCOUNT_DOES_NOT_EXIST',
  CREDENTIALS_DO_NOT_MATCH: 'CREDENTIALS_DO_NOT_MATCH',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INVALID_TOKEN: 'INVALID_TOKEN',
} as const;
